<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Climate Change</title>
    <link rel="shortcut icon" href="pics\Logo.ico" type="image/x-icon">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="style_article.css">
    <link rel="stylesheet" href="style_about.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="script.js"></script>
</head>

<body class="home fade-in">

    <nav role='navigation' id="nav">
        <a data-page="home" class="active" href="index.php">Home</a>
        <a data-page="solution" class="" href="solution.php">Solution</a>
        <a data-page="survey" class="" href="survey.php">Survey</a>
        <a data-page="about" class="" href="about.php">About</a>
    </nav>

    <div id="title_div_homepage">
        <img src="pics\Logo.png" alt="Kilecy" style="background: rgba(255, 255, 255, 0.5); float: none; border-radius: 15px; margin: 20px;">
        <h1 id="title" class="title_homepage">CLIMATE CHANGE</h1>
    </div>

    <article>
        <h2>Introduction</h2>
        <p class="tag">A long-term change in the average weather patterns that have come to characterize Earth's local, regional, and global climates is referred to as climate change. The world's temperature is ideal for all living organisms to survive. A balance is needed to maintain this temperature. The sun's heat is transmitted to the earth, which warms it. The cool effect is created by the sun's heat bouncing back to space. The climate changes when this equilibrium is broken. As a result, climate change is an actual change in weather rate that occurs in a specific region.</p>
        <br><br>
        <p class="tag">Climate change is one of the most problems our country faces. Not our country only but the whole world. This problem has a lot of causes, but the main cause is when greenhouse gases are emitted and trapped in the earth, the greenhouse effect occurs, resulting in climate change. The greenhouse effect creates a shield around the earth's atmosphere that traps heat from the sun and keeps our atmosphere cooler, similar to a greenhouse.</p>
        <br><br>
        <h3 id="h3_tag">Carbon dioxide (CO<sub>2</sub>):</h3>
        <p class="tag no_margin_left">Carbon dioxide is emitted when fossil fuels such as coal, oil, and natural gas are burned, as well as when trees and other plants are burned or cut down. Carbon dioxide accounted for 81% of all greenhouse gas emissions caused by humans. Methane (CH<sub>4</sub>): Methane gas accounted for 10% of all greenhouse gases. Nitrous oxide (N<sub>2</sub>O): Nitrogen oxide is generated by agriculture, fossil fuels, industry, and waste-water treatment. Nitrous oxide accounted for 7% of greenhouse gas emissions.</p>
        <br><br>
        <h2>Causes</h2>
        <p class="tag">Carbon dioxide and nitrous oxide are produced when coal, oil, and gas are burned. Trees help to control the environment by removing carbon dioxide gas from the atmosphere, which is why they are being cut down (deforestation). As a result, when trees are cut down, the beneficial effect is lost, and the carbon contained in the trees is released into the environment, leading to the greenhouse effect. Fertilizers that contain nitrogen emit nitrous oxide.</p>
        <br><br>
        <h2>Impacts</h2>
        <p class="p_introductory" class="tag">Climate change problem has effects on some majors like:</p>
        <br><br>
        <h3>Food:</h3>
        <p class="tag no_margin_left">Climate and weather patterns have an effect on our food supply. Agricultural practices may be adaptable, but changes such as rising temperatures, water stress, diseases, and weather extremes pose challenges for farmers and ranchers who cultivate the plants.</p>
        <br><br>
        <h3>Health:</h3>
        <p class="tag no_margin_left">Climate change puts human health at risk. More heat stress, an increase in waterborne diseases, poor air quality, and diseases spread by insects and rodents are expected as a result of the changing climate. Many of these health hazards can be compounded by severe weather events.</p>
        <br><br>
        <h3>Environment:</h3>
        <p class="tag no_margin_left">Climate change has an effect on ecosystem as well. For example, habitats are evolving, the timing of events like flowering and egg-laying is shifting, and species' home ranges are shifting. Changes are also taking place in the ocean. The ocean absorbs about 30% of the carbon dioxide emitted into the atmosphere as a result of fossil fuel combustion. As a result, the ocean is becoming more acidic, which has an effect on marine life. In the coastal areas, droughts are taking place because of the global warming that melts ice at the poles, rising the level of the seas. Consequently, droughts are happening.</p>
    </article>
 
    <script>
        window.scrollBy(0, 1);
        window.scrollBy(0, -1);
    </script>
</body>

</html>